# Generated by Django 5.2 on 2025-04-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sessionverification_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionVerification',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='session_number',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
