# Generated by Django 5.2 on 2025-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_sessionverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
